### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by AdamSaleh**

### CODE REVIEW

**Comment by danielpassos** [comment]
@AdamSaleh DO NOT MERGE???

**Comment by smiklosovic** [comment]
@danielpassos seems like Adam uses GitHub as a backup system :)

**Comment by danielpassos** [comment]
@smiklosovic He always can use a branch for it ;)

Closing that!

**Comment by matzew** [comment]
>  He always can use a branch for it ;) Closing that!

well, if that's what the QE does on their -tests repos, that's fine for me ...

**Comment by TadeasKriz** [comment]
@danielpassos We use PR, but we don't merge, we rebase. The 'DO NOT MERGE' is a reminder to not use the merge button on github.

**Comment by abstractj** [comment]
@matzew -1 on it or encourage it

**Pull request closed without merging**
